# Generated by Django 5.0.7 on 2024-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_journal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
        migrations.AddField(
            model_name='therapist',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='therapists/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapist',
            name='specialization',
            field=models.CharField(max_length=255),
        ),
    ]
