# Generated by Django 5.0.7 on 2024-07-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_therapist_bio_remove_therapist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='available_slots',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapist',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
