# Generated by Django 5.0.7 on 2024-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_therapist_available_slots_therapist_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='about',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='languages',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
