# Generated by Django 5.0.7 on 2024-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_quiz_created_at_remove_quiz_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
