# Generated by Django 5.0.7 on 2024-07-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_choice_is_correct_choice_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='score',
            new_name='is_correct',
        ),
    ]
