# Generated by Django 5.0.7 on 2024-07-23 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_choice_score_alter_choice_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaAsana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='yoga_asanas/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YogaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.TextField()),
                ('benefits', models.TextField()),
                ('precautions', models.TextField()),
                ('asana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.yogaasana')),
            ],
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.RemoveField(
            model_name='supportgroup',
            name='members',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='SupportGroup',
        ),
    ]
