# Generated by Django 5.0.7 on 2024-07-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_yogaasana_yogadetail_delete_forum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogadetail',
            name='precautions',
        ),
        migrations.AddField(
            model_name='yogadetail',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
